name = "DocExample"
uuid = "d2931bb0-0ff3-4fee-972b-bc9fa6c50db3"
authors = ["Alena I. Skorobogatova <51082045+alenskorobogatova@users.noreply.github.com>"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
